# Netlify Configuration for PartyMotivator i18n

[build]
  publish = "dist"
  command = "npm run build"

# Edge Functions Configuration
[[edge_functions]]
  function = "locale-redirect"
  path = "/"

# Redirects and Rewrites
[[redirects]]
  # SPA fallback for all localized routes
  from = "/de/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/en/*" 
  to = "/index.html"
  status = 200

# Headers for SEO and Performance
[[headers]]
  for = "/"
  [headers.values]
    Vary = "Accept-Language"
    
[[headers]]
  for = "/de/*"
  [headers.values]
    Content-Language = "de"
    
[[headers]]
  for = "/en/*"
  [headers.values]
    Content-Language = "en"

# Static Assets Caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
